# yaml-language-server: $schema=https://blue-build.org
name: glint-linux 
description: Luv u Glint
image-version: latest # <--- THIS REPLACES THE RAW "RAWHIDE" TAG TRAP

base-image: ghcr.io/fedora-linux/fedora-kinoite

modules:
  - type: script
    scripts:
      - glint-setup.sh
