name: glint-linux 
description: Luv u Glint
image-version: rawhide
base-image: quay.io/fedora-ostree-desktops/kinoite

modules:
  - type: dnf
    install:
      packages:
        - wine-core
        - wine-common
        - gamemode         
        - powertop         
        - fastfetch        
        - mesa-va-drivers  
        - intel-media-driver
        - NetworkManager-wifi
        - bluez
        - bluez-utils
        - pipewire-utils
        - openjdk21
        - openjdk21-fastload

  - type: script
    scripts:
      - glint-setup.sh
