name: Build ISO
on:
  workflow_dispatch:

env:
  IMAGE_NAME: glint-linux
  IMAGE_TAG: latest

jobs:
  build-iso:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build ISO Installer
        uses: jasonn3/build-container-installer@v1.2.4
        id: build
        with:
          arch: x86_64
          image_name: ${{ env.IMAGE_NAME }}
          image_repo: ghcr.io/nulltoast00
          image_tag: ${{ env.IMAGE_TAG }}
          version: '41'
          variant: 'Kinoite'

      - name: Save ISO to Summary Page
        uses: actions/upload-artifact@v4
        with:
          name: glint-linux-kinoite-iso
          path: /home/runner/work/**/*.iso
          if-no-files-found: error
